// source: school.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var student_pb = require('./student_pb.js');
goog.object.extend(proto, student_pb);
var teacher_pb = require('./teacher_pb.js');
goog.object.extend(proto, teacher_pb);
var response_pb = require('./response_pb.js');
goog.object.extend(proto, response_pb);
goog.exportSymbol('proto.school.AddStudentsToTeacherRequest', null, global);
goog.exportSymbol('proto.school.RegisterRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.school.RegisterRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.school.RegisterRequest.repeatedFields_, null);
};
goog.inherits(proto.school.RegisterRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.school.RegisterRequest.displayName = 'proto.school.RegisterRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.school.AddStudentsToTeacherRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.school.AddStudentsToTeacherRequest.repeatedFields_, null);
};
goog.inherits(proto.school.AddStudentsToTeacherRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.school.AddStudentsToTeacherRequest.displayName = 'proto.school.AddStudentsToTeacherRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.school.RegisterRequest.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.school.RegisterRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.school.RegisterRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.school.RegisterRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.school.RegisterRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    teachersList: jspb.Message.toObjectList(msg.getTeachersList(),
    teacher_pb.teacher.toObject, includeInstance),
    studentsList: jspb.Message.toObjectList(msg.getStudentsList(),
    student_pb.student.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.school.RegisterRequest}
 */
proto.school.RegisterRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.school.RegisterRequest;
  return proto.school.RegisterRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.school.RegisterRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.school.RegisterRequest}
 */
proto.school.RegisterRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new teacher_pb.teacher;
      reader.readMessage(value,teacher_pb.teacher.deserializeBinaryFromReader);
      msg.addTeachers(value);
      break;
    case 2:
      var value = new student_pb.student;
      reader.readMessage(value,student_pb.student.deserializeBinaryFromReader);
      msg.addStudents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.school.RegisterRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.school.RegisterRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.school.RegisterRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.school.RegisterRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeachersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      teacher_pb.teacher.serializeBinaryToWriter
    );
  }
  f = message.getStudentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      student_pb.student.serializeBinaryToWriter
    );
  }
};


/**
 * repeated teacher teachers = 1;
 * @return {!Array<!proto.school.teacher>}
 */
proto.school.RegisterRequest.prototype.getTeachersList = function() {
  return /** @type{!Array<!proto.school.teacher>} */ (
    jspb.Message.getRepeatedWrapperField(this, teacher_pb.teacher, 1));
};


/**
 * @param {!Array<!proto.school.teacher>} value
 * @return {!proto.school.RegisterRequest} returns this
*/
proto.school.RegisterRequest.prototype.setTeachersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.school.teacher=} opt_value
 * @param {number=} opt_index
 * @return {!proto.school.teacher}
 */
proto.school.RegisterRequest.prototype.addTeachers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.school.teacher, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.school.RegisterRequest} returns this
 */
proto.school.RegisterRequest.prototype.clearTeachersList = function() {
  return this.setTeachersList([]);
};


/**
 * repeated student students = 2;
 * @return {!Array<!proto.school.student>}
 */
proto.school.RegisterRequest.prototype.getStudentsList = function() {
  return /** @type{!Array<!proto.school.student>} */ (
    jspb.Message.getRepeatedWrapperField(this, student_pb.student, 2));
};


/**
 * @param {!Array<!proto.school.student>} value
 * @return {!proto.school.RegisterRequest} returns this
*/
proto.school.RegisterRequest.prototype.setStudentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.school.student=} opt_value
 * @param {number=} opt_index
 * @return {!proto.school.student}
 */
proto.school.RegisterRequest.prototype.addStudents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.school.student, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.school.RegisterRequest} returns this
 */
proto.school.RegisterRequest.prototype.clearStudentsList = function() {
  return this.setStudentsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.school.AddStudentsToTeacherRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.school.AddStudentsToTeacherRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.school.AddStudentsToTeacherRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.school.AddStudentsToTeacherRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.school.AddStudentsToTeacherRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    teacher: (f = msg.getTeacher()) && teacher_pb.teacher.toObject(includeInstance, f),
    studentsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.school.AddStudentsToTeacherRequest}
 */
proto.school.AddStudentsToTeacherRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.school.AddStudentsToTeacherRequest;
  return proto.school.AddStudentsToTeacherRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.school.AddStudentsToTeacherRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.school.AddStudentsToTeacherRequest}
 */
proto.school.AddStudentsToTeacherRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new teacher_pb.teacher;
      reader.readMessage(value,teacher_pb.teacher.deserializeBinaryFromReader);
      msg.setTeacher(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addStudents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.school.AddStudentsToTeacherRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.school.AddStudentsToTeacherRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.school.AddStudentsToTeacherRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.school.AddStudentsToTeacherRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeacher();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      teacher_pb.teacher.serializeBinaryToWriter
    );
  }
  f = message.getStudentsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional teacher teacher = 1;
 * @return {?proto.school.teacher}
 */
proto.school.AddStudentsToTeacherRequest.prototype.getTeacher = function() {
  return /** @type{?proto.school.teacher} */ (
    jspb.Message.getWrapperField(this, teacher_pb.teacher, 1));
};


/**
 * @param {?proto.school.teacher|undefined} value
 * @return {!proto.school.AddStudentsToTeacherRequest} returns this
*/
proto.school.AddStudentsToTeacherRequest.prototype.setTeacher = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.school.AddStudentsToTeacherRequest} returns this
 */
proto.school.AddStudentsToTeacherRequest.prototype.clearTeacher = function() {
  return this.setTeacher(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.school.AddStudentsToTeacherRequest.prototype.hasTeacher = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string students = 2;
 * @return {!Array<string>}
 */
proto.school.AddStudentsToTeacherRequest.prototype.getStudentsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.school.AddStudentsToTeacherRequest} returns this
 */
proto.school.AddStudentsToTeacherRequest.prototype.setStudentsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.school.AddStudentsToTeacherRequest} returns this
 */
proto.school.AddStudentsToTeacherRequest.prototype.addStudents = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.school.AddStudentsToTeacherRequest} returns this
 */
proto.school.AddStudentsToTeacherRequest.prototype.clearStudentsList = function() {
  return this.setStudentsList([]);
};


goog.object.extend(exports, proto.school);
