/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.0
 * source: student.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace school {
    export class Student extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            isSuspended?: boolean;
            teachers?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [6], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("firstName" in data && data.firstName != undefined) {
                    this.firstName = data.firstName;
                }
                if ("lastName" in data && data.lastName != undefined) {
                    this.lastName = data.lastName;
                }
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("isSuspended" in data && data.isSuspended != undefined) {
                    this.isSuspended = data.isSuspended;
                }
                if ("teachers" in data && data.teachers != undefined) {
                    this.teachers = data.teachers;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get firstName() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set firstName(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get lastName() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set lastName(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get isSuspended() {
            return pb_1.Message.getFieldWithDefault(this, 5, false) as boolean;
        }
        set isSuspended(value: boolean) {
            pb_1.Message.setField(this, 5, value);
        }
        get teachers() {
            return pb_1.Message.getFieldWithDefault(this, 6, []) as string[];
        }
        set teachers(value: string[]) {
            pb_1.Message.setField(this, 6, value);
        }
        static fromObject(data: {
            id?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            isSuspended?: boolean;
            teachers?: string[];
        }): Student {
            const message = new Student({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.firstName != null) {
                message.firstName = data.firstName;
            }
            if (data.lastName != null) {
                message.lastName = data.lastName;
            }
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.isSuspended != null) {
                message.isSuspended = data.isSuspended;
            }
            if (data.teachers != null) {
                message.teachers = data.teachers;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: string;
                firstName?: string;
                lastName?: string;
                email?: string;
                isSuspended?: boolean;
                teachers?: string[];
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.firstName != null) {
                data.firstName = this.firstName;
            }
            if (this.lastName != null) {
                data.lastName = this.lastName;
            }
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.isSuspended != null) {
                data.isSuspended = this.isSuspended;
            }
            if (this.teachers != null) {
                data.teachers = this.teachers;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id.length)
                writer.writeString(1, this.id);
            if (this.firstName.length)
                writer.writeString(2, this.firstName);
            if (this.lastName.length)
                writer.writeString(3, this.lastName);
            if (this.email.length)
                writer.writeString(4, this.email);
            if (this.isSuspended != false)
                writer.writeBool(5, this.isSuspended);
            if (this.teachers.length)
                writer.writeRepeatedString(6, this.teachers);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Student {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Student();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readString();
                        break;
                    case 2:
                        message.firstName = reader.readString();
                        break;
                    case 3:
                        message.lastName = reader.readString();
                        break;
                    case 4:
                        message.email = reader.readString();
                        break;
                    case 5:
                        message.isSuspended = reader.readBool();
                        break;
                    case 6:
                        pb_1.Message.addToRepeatedField(message, 6, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Student {
            return Student.deserialize(bytes);
        }
    }
}
